// Per-family palettes for the landing pages. Each theme is applied via
// CSS custom properties on the page root, then read with bg-[var(--*)] etc.
// This lets us keep one shared layout while giving every family a distinct feel.

export const THEMES = {
  lap: {
    family: "LAP",
    name: "Coral Sunrise",
    vars: {
      "--ld-bg":         "#FFF6EE",
      "--ld-bg-2":       "#FFEAD8",
      "--ld-surface":    "#FFFFFF",
      "--ld-rule":       "#F0DCC6",
      "--ld-ink":        "#2A1810",
      "--ld-ink-soft":   "#6B5444",
      "--ld-ink-mute":   "#8C7762",
      "--ld-accent":     "#E85D2E",
      "--ld-accent-2":   "#B7421B",
      "--ld-accent-soft":"#FCE2D2",
      "--ld-glow":       "rgba(232,93,46,0.18)",
      "--ld-hero-bg":    "#1A0F08",
      "--ld-hero-ink":   "#FFEAD8",
    },
  },
  lrd: {
    family: "LRD",
    name: "Deep Teal",
    vars: {
      "--ld-bg":         "#F1F8F6",
      "--ld-bg-2":       "#DCEEEA",
      "--ld-surface":    "#FFFFFF",
      "--ld-rule":       "#C8DDD7",
      "--ld-ink":        "#0E2926",
      "--ld-ink-soft":   "#3F5C57",
      "--ld-ink-mute":   "#6B7F7B",
      "--ld-accent":     "#0F766E",
      "--ld-accent-2":   "#0A4F49",
      "--ld-accent-soft":"#CCE6E2",
      "--ld-glow":       "rgba(15,118,110,0.18)",
      "--ld-hero-bg":    "#062521",
      "--ld-hero-ink":   "#DCEEEA",
    },
  },
  las: {
    family: "LAS",
    name: "Violet Noir",
    vars: {
      "--ld-bg":         "#F5F2FB",
      "--ld-bg-2":       "#E9E1F7",
      "--ld-surface":    "#FFFFFF",
      "--ld-rule":       "#D6CAE8",
      "--ld-ink":        "#1F1240",
      "--ld-ink-soft":   "#4F3F6F",
      "--ld-ink-mute":   "#7866A0",
      "--ld-accent":     "#6D3FBF",
      "--ld-accent-2":   "#4A2596",
      "--ld-accent-soft":"#E5DAF6",
      "--ld-glow":       "rgba(109,63,191,0.18)",
      "--ld-hero-bg":    "#170A33",
      "--ld-hero-ink":   "#E9E1F7",
    },
  },
  hl: {
    family: "HL",
    name: "Warm Rose",
    vars: {
      "--ld-bg":         "#FDF3F4",
      "--ld-bg-2":       "#F8E1E4",
      "--ld-surface":    "#FFFFFF",
      "--ld-rule":       "#EFC9CE",
      "--ld-ink":        "#2C1217",
      "--ld-ink-soft":   "#5C3641",
      "--ld-ink-mute":   "#876069",
      "--ld-accent":     "#C2365A",
      "--ld-accent-2":   "#8E1F3E",
      "--ld-accent-soft":"#F5D5DD",
      "--ld-glow":       "rgba(194,54,90,0.18)",
      "--ld-hero-bg":    "#22090F",
      "--ld-hero-ink":   "#F8E1E4",
    },
  },
  bl: {
    family: "BL",
    name: "Sage Olive",
    vars: {
      "--ld-bg":         "#F4F5EE",
      "--ld-bg-2":       "#E2E5D2",
      "--ld-surface":    "#FFFFFF",
      "--ld-rule":       "#CFD3B9",
      "--ld-ink":        "#1A1F0E",
      "--ld-ink-soft":   "#4A523A",
      "--ld-ink-mute":   "#6F7A5F",
      "--ld-accent":     "#4F7A28",
      "--ld-accent-2":   "#365418",
      "--ld-accent-soft":"#D6E1BF",
      "--ld-glow":       "rgba(79,122,40,0.18)",
      "--ld-hero-bg":    "#0F1407",
      "--ld-hero-ink":   "#E2E5D2",
    },
  },
  pl: {
    family: "PL",
    name: "Graphite Spark",
    vars: {
      "--ld-bg":         "#F4F5F8",
      "--ld-bg-2":       "#E2E4EA",
      "--ld-surface":    "#FFFFFF",
      "--ld-rule":       "#CDD1DA",
      "--ld-ink":        "#10141C",
      "--ld-ink-soft":   "#3A4253",
      "--ld-ink-mute":   "#697080",
      "--ld-accent":     "#1E40AF",
      "--ld-accent-2":   "#142C7A",
      "--ld-accent-soft":"#D5DEF6",
      "--ld-glow":       "rgba(30,64,175,0.18)",
      "--ld-hero-bg":    "#070A12",
      "--ld-hero-ink":   "#E2E4EA",
    },
  },
};
